# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      enable-dependency-uno:
        type: boolean
        description: Enable dependency uno


      enable-hello-action:
        type: boolean
        description: Enable Hello Action
      enable-add-action:
        type: boolean
        description: Enable Add Action        
      add-action-first-value:
        type: string
        description: First Value To Add
      add-action-second-value:
        type: string
        description: Second Value To Add
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 PrimaryMain:
    runs-on: ubuntu-latest
    name: Primary Main Job
    steps:
      - uses: actions/checkout@main
      - id: foo
        name: Composite Step
        uses: rzmudzin/hello-world-composite-action@main
        with:
          who-to-greet: 'Mona the Octocat'
          secrets: ${{ toJSON(secrets) }}
          actionInputs: ${{ toJSON(inputs) }}
      - name: Composite Step Consumer 
        run: |
          echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
 dependency-uno:
   if: ${{ inputs.enable-dependency-uno }}
   runs-on: macOS-latest
   outputs:
     uniqueVMActionsTag: ${{ steps.dependency-uno-step1.outputs.test }}
     vmName: ${{ steps.dependency-uno-step1.outputs.randomnumber }}   
   steps:
   - id: dependency-uno-step1
     name: Dependency Step
     run: |
       echo "Executing job depenency"  
       echo "randomnumber=$(echo $RANDOM)" >> $GITHUB_OUTPUT
       echo "test=Testing With Spaces" >> $GITHUB_OUTPUT
 job-with-dependencies:
   needs: [dependency-uno]
   runs-on: macOS-latest
   steps:
   - name: Step requiring dependency be run first
     run: |
       echo "Running after dependency is run"  
       echo "I'm running on ${{ needs.dependency-uno.outputs.uniqueVMActionsTag }}"
       echo "With the name ${{ needs.dependency-uno.outputs.vmName }}"
       echo "Done"

